version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wprestpageinfo_wp
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

  db:
    image: mysql:5.7
    container_name: wprestpageinfo_db
    restart: always
    ports:
      - 3306:3306
    user: '1000:50'
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./sql:/sql
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: